const tempData = [
  {
    id: 1,
    name: "Vere Readhead",
    email: "vreadhead0@google.com.au",
    role: "Research Nurse",
    age: 23,
    dob: "2022-03-27",
    address: "7275 Petterle Avenue",
    city: "Detchino",
    state: null,
  },
  {
    id: 2,
    name: "Cheryl Neighbour",
    email: "cneighbour1@buzzfeed.com",
    role: "Staff Accountant II",
    age: 100,
    dob: "2021-09-25",
    address: "8179 Coolidge Avenue",
    city: "Rancabugel",
    state: null,
  },
  {
    id: 3,
    name: "Sunshine Bettleson",
    email: "sbettleson2@webs.com",
    role: "Director of Sales",
    age: 73,
    dob: "2022-04-13",
    address: "79764 Melrose Lane",
    city: "Gandoang",
    state: null,
  },
  {
    id: 4,
    name: "Estrellita Diche",
    email: "ediche3@amazonaws.com",
    role: "Budget/Accounting Analyst I",
    age: 44,
    dob: "2022-03-26",
    address: "0545 Arapahoe Point",
    city: "Kuangsan",
    state: null,
  },
  {
    id: 5,
    name: "Frannie Laurencot",
    email: "flaurencot4@utexas.edu",
    role: "Senior Cost Accountant",
    age: 28,
    dob: "2021-07-17",
    address: "61299 Westerfield Alley",
    city: "Vredenburg",
    state: null,
  },
  {
    id: 6,
    name: "Daveta Alpe",
    email: "dalpe5@cmu.edu",
    role: "Help Desk Technician",
    age: 45,
    dob: "2021-09-15",
    address: "39 Sugar Lane",
    city: "'s-Hertogenbosch",
    state: "Provincie Noord-Brabant",
  },
  {
    id: 7,
    name: "Gawen Alfuso",
    email: "galfuso6@redcross.org",
    role: "Senior Developer",
    age: 48,
    dob: "2021-12-18",
    address: "34851 Amoth Terrace",
    city: "Lanas",
    state: null,
  },
  {
    id: 8,
    name: "Violette Demeter",
    email: "vdemeter7@issuu.com",
    role: "Software Engineer I",
    age: 66,
    dob: "2021-09-07",
    address: "356 Ronald Regan Avenue",
    city: "São Miguel do Araguaia",
    state: null,
  },
  {
    id: 9,
    name: "Agathe Bubb",
    email: "abubb8@cnbc.com",
    role: "Senior Cost Accountant",
    age: 89,
    dob: "2021-11-07",
    address: "9 4th Parkway",
    city: "Buffalo",
    state: "New York",
  },
  {
    id: 10,
    name: "Kathe Skace",
    email: "kskace9@bloglines.com",
    role: "Assistant Manager",
    age: 35,
    dob: "2021-10-12",
    address: "7757 Drewry Terrace",
    city: "P’rimorsk’oe",
    state: null,
  },
  {
    id: 11,
    name: "Idaline Muller",
    email: "imullera@scribd.com",
    role: "Information Systems Manager",
    age: 23,
    dob: "2022-01-08",
    address: "093 Chinook Point",
    city: "Vaxholm",
    state: "Stockholm",
  },
  {
    id: 12,
    name: "Randy Dauby",
    email: "rdaubyb@lycos.com",
    role: "Structural Analysis Engineer",
    age: 74,
    dob: "2021-06-05",
    address: "5799 Spohn Road",
    city: "Flushing",
    state: "New York",
  },
  {
    id: 13,
    name: "Gerta Tarpey",
    email: "gtarpeyc@blinklist.com",
    role: "Marketing Manager",
    age: 84,
    dob: "2021-08-19",
    address: "7 Mccormick Junction",
    city: "Coris",
    state: null,
  },
  {
    id: 14,
    name: "Lucille Auden",
    email: "laudend@un.org",
    role: "Data Coordiator",
    age: 61,
    dob: "2021-09-26",
    address: "426 Jana Parkway",
    city: "Boulogne-Billancourt",
    state: "Île-de-France",
  },
  {
    id: 15,
    name: "Karlik Stribling",
    email: "kstriblinge@jigsy.com",
    role: "Actuary",
    age: 99,
    dob: "2021-07-21",
    address: "8 Harper Court",
    city: "Oslo",
    state: "Oslo",
  },
  {
    id: 16,
    name: "Del Dimbylow",
    email: "ddimbylowf@behance.net",
    role: "Senior Sales Associate",
    age: 44,
    dob: "2021-05-28",
    address: "759 Upham Circle",
    city: "Libas",
    state: null,
  },
  {
    id: 17,
    name: "Layney Dyer",
    email: "ldyerg@live.com",
    role: "Financial Advisor",
    age: 66,
    dob: "2022-03-28",
    address: "94 Fordem Crossing",
    city: "Zhuxing Chaoxianzu",
    state: null,
  },
  {
    id: 18,
    name: "Henderson Taplow",
    email: "htaplowh@google.co.uk",
    role: "Software Test Engineer III",
    age: 78,
    dob: "2022-02-01",
    address: "25 Anderson Pass",
    city: "Paatan",
    state: null,
  },
  {
    id: 19,
    name: "Stacia Letertre",
    email: "sletertrei@constantcontact.com",
    role: "Help Desk Operator",
    age: 84,
    dob: "2022-01-22",
    address: "06412 Kings Road",
    city: "Belle-Anse",
    state: null,
  },
  {
    id: 20,
    name: "Lin Radenhurst",
    email: "lradenhurstj@msn.com",
    role: "Account Coordinator",
    age: 24,
    dob: "2021-07-15",
    address: "9098 Di Loreto Avenue",
    city: "Mwembe",
    state: null,
  },
];
export default tempData;
