export const FETCH_EMPLOYEE_DATA_REQUEST = "FETCH_EMPLOYEE_DATA_REQUEST";
export const FETCH_EMPLOYEE_DATA_SUCCESS = "FETCH_EMPLOYEE_DATA_SUCCESS";
export const FETCH_EMPLOYEE_DATA_FAILURE = "FETCH_EMPLOYEE_DATA_FAILURE";
